# Generated by Django 3.0.8 on 2021-10-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0002_product_subcategoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoryproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_product', to='category.SubcategoryProduct'),
        ),
    ]
